### ISSUE TITLE
Parsing failure impossible to diagnose

### ISSUE THREAD

**Issue by Shotgun167** [snipsco/snips-nlu-ontology#138]
If you have a syntax error in a yaml training file, Snips will tell you something like:

Missing ending ']' in annotated utterance"

Good luck finding which utterance is missing that bracket.  

I found that adding " + state.input" to the exception string in input.py/capture_slot and input.py/capture_tagged would print the utterance, so that the fix was quick.

**Comment by adrienball** [comment]
I'm closing this as it's a duplicate of https://github.com/snipsco/snips-nlu/issues/794
